### ISSUE TITLE
can't find hashed state string of new_state_str

### ISSUE THREAD

**Issue by ultrazhl98** [Zsbyqx20/DroidTask_DataOverview#1]
Thanks for your great job! I have some questions about the dataset.
1. when I look task1.yaml, I can't find the new_state_str'id in the folder of states_view_ids.
2. what's the meaning of the number behind Choice, such as Choice: -1, Choice: 3.

**Comment by Zsbyqx20** [comment]
1. As the **README.md**, you can find the related `state_str` in the `.json` files in `states` folder, instead of `states_view_ids`.
2. The number of choices matches the element id in the **HTML string** below the `State` entry. Meanwhile, choosing `-1` means the task has been finished, and there is no need for a **next** step.

Hope this will help. 😃
